### ISSUE TITLE
mastodon user home

### ISSUE THREAD

**Issue by kdpuvvadi** [geerlingguy/ansible-mastodon#4]
As per official documentation, source files will be on `/home/mastodon/live`. And in vars, webroot is already mentioned as `/home/mastodon/live/public. Reason for not creating user account?

**Comment by geerlingguy** [comment]
The user account should be set up here: https://github.com/geerlingguy/ansible-mastodon/blob/master/tasks/users.yml#L27-L32

Though I didn't realize it needed a homedir.

**Comment by kdpuvvadi** [comment]
> The user account should be set up here: https://github.com/geerlingguy/ansible-mastodon/blob/master/tasks/users.yml#L27-L32
> 
> Though I didn't realize it needed a homedir.

`    create_home: false` this is i was talking about.

**Comment by geerlingguy** [comment]
I'll yank that so it does create a homedir, then!
